### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "electron-events". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by QWXL** [kisstar/electron-events#7]
Uncaught TypeError: Failed to resolve module specifier "electron-events". Relative references must start with either "/", "./", or "../".
I use `import { useEvents } from 'electron-events';` In renderer
I dont know what happen

**Comment by kisstar** [comment]
If you haven't used bundle tools like [Vite](https://vitejs.dev/guide/), [Rollup](https://rollupjs.org/), and [Webpack](https://webpack.js.org/), and so on, then you can't directly use third-party modules in your rendering process because the JavaScript ES Module doesn't recognize them.
You can check the official documentation of these tools to modify your application, or use some open-source CLI tools to quickly build a project.
Of course, you can also use the following syntax to load the `electron-events` module:
```js
const electronEvents = require('electron-events')

const events = electronEvents.useEvents();

events.on('main' /* Name of the main process */, 'say_hi', text => {
  console.log(text);
});
```
But this requires you to add the following configuration when creating the main window:
```js
new BrowserWindow({
  // ...
  webPreferences: {
    // preload: path.join(__dirname, 'preload.js'),
    nodeIntegration : true,
    contextIsolation : false
  }
});
```
In fact, we do not recommend doing so as it may lead to some security issues. You can refer to the [official documentation](https://www.electronjs.org/docs/latest/tutorial/security) for more information.

**Comment by QWXL** [comment]
Oh ,allright , look like i should use electron ipc to do that
thanks for u reply
